#!/bin/bash

# Soroban Contract Deployment Guide for Stellar NFT Marketplace
# This script provides instructions for real deployment to Stellar testnet

echo "🚀 Soroban Contract Deployment Guide"
echo "===================================="
echo ""

echo "📋 Prerequisites:"
echo "1. Install Soroban CLI: https://soroban.stellar.org/docs/getting-started/setup"
echo "2. Create/fund a Stellar testnet account"
echo "3. Install Node.js dependencies: npm install"
echo ""

echo "🔑 Step 1: Set up your testnet account"
echo "--------------------------------------"
echo "# Create a new keypair for deployment"
echo "soroban keys generate deployer --network testnet"
echo ""
echo "# Fund your account (get testnet XLM from friendbot)"
echo "curl 'https://friendbot.stellar.org/?addr=<YOUR_PUBLIC_KEY>'"
echo ""

echo "📦 Step 2: Deploy NFT Contract"
echo "------------------------------"
echo "# Deploy the NFT contract"
echo "soroban contract deploy \\"
echo "  --wasm stellar-nft.wasm \\"
echo "  --source deployer \\"
echo "  --network testnet"
echo ""
echo "# Initialize the NFT contract"
echo "soroban contract invoke \\"
echo "  --id <NFT_CONTRACT_ID> \\"
echo "  --source deployer \\"
echo "  --network testnet \\"
echo "  -- \\"
echo "  initialize \\"
echo "  --admin <YOUR_PUBLIC_KEY>"
echo ""

echo "📦 Step 3: Deploy Auction Contract"
echo "----------------------------------"
echo "# Deploy the auction contract"
echo "soroban contract deploy \\"
echo "  --wasm stellar-auction.wasm \\"
echo "  --source deployer \\"
echo "  --network testnet"
echo ""
echo "# Initialize the auction contract"
echo "soroban contract invoke \\"
echo "  --id <AUCTION_CONTRACT_ID> \\"
echo "  --source deployer \\"
echo "  --network testnet \\"
echo "  -- \\"
echo "  initialize \\"
echo "  --admin <YOUR_PUBLIC_KEY>"
echo ""

echo "⚙️ Step 4: Update Configuration"
echo "------------------------------"
echo "# Update src/config/contracts.json with real contract IDs"
echo "nano src/config/contracts.json"
echo ""

echo "🧪 Step 5: Test Deployment"
echo "-------------------------"
echo "# Test NFT minting"
echo "soroban contract invoke \\"
echo "  --id <NFT_CONTRACT_ID> \\"
echo "  --source deployer \\"
echo "  --network testnet \\"
echo "  -- \\"
echo "  mint \\"
echo "  --to <YOUR_PUBLIC_KEY> \\"
echo "  --name 'Test NFT' \\"
echo "  --description 'Test Description' \\"
echo "  --image_url 'https://example.com/image.png' \\"
echo "  --attributes '[]' \\"
echo "  --royalty_percentage 5"
echo ""

echo "🎉 Deployment Complete!"
echo "----------------------"
echo "Your contracts are now live on Stellar testnet!"
echo "Update your frontend to use the real contract IDs."
